#!/bin/bash

js=game.js

rm $js
echo "'use strict';" > $js
cat src/error.js >> $js
cat src/utils.js >> $js
cat src/loader.js >> $js
cat src/trees.js >> $js
cat src/tracks.js >> $js
cat src/tramstop.js >> $js
cat src/tramline.js >> $js
cat src/tile.js >> $js
cat src/map.js >> $js
cat src/driver.js >> $js
cat src/cardriver.js >> $js
cat src/tramdriver.js >> $js
cat src/bezier.js >> $js
cat src/vehicle.js >> $js
cat src/car.js >> $js
cat src/tram.js >> $js
cat src/ui.js >> $js
cat src/main.js >> $js
