#!/bin/bash

js=game.js

rm $js
cat src/error.js >> $js
cat src/utils.js >> $js
cat src/loader.js >> $js
cat src/trees.js >> $js
cat src/tracks.js >> $js
cat src/tile.js >> $js
cat src/map.js >> $js
cat src/carai.js >> $js
cat src/bezier.js >> $js
cat src/car.js >> $js
cat src/ui.js >> $js
cat src/main.js >> $js
